[package]
name = "http-to-nats-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.45"
axum = "0.7"
futures = "0.3.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
